# do not touch until you know what you are doing especially for rookies --vijay
x-app-depends-on: &app-depends-on
    - mysql
version: 1.0.0
services:
    mysql:
        build: docker/mysql
        tty: true
        ports:
        - "3306:3306"
        container_name: mysql
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: yes
            MYSQL_DATABASE: practice
    app:
        build: docker/app
        tty: true
        env_file: .env
        ports:
        - "80:80"
        container_name: app
        depends_on: *app-depends-on
        volumes:
        - ./:/var/www/nothing_todo
        - ./docker/conf:/etc/apache2/sites-available
